export interface formData {
  IdDistribuidor: number;
  tipoPersona: string;
  razonSocial: string;
  nombreComercial: string;
  rfc: string;
  regimenFiscal: string;
  usoCFDI: string;
  correoFactura: string;
  calleFiscal: string;
  numExtFiscal: string;
  numIntFiscal: string;
  codigoPostalFiscal: string;
  coloniaFiscal: string;
  telefonoFiscal: string;
  whatsappFiscal: string;
  estadoFiscal: string;
  idMunicipio: string;
  ciudadFiscal: string;
  actSHCPFiscal: string;
  nombreLegalFiscal: string;
  nombreCompras: string;
  apellidoCompras: string;
  correoCompras: string;
  telefonoCompras: string;
  extensionCompras: string;
  whatsappCompras: string;
  nombrePago: string;
  apellidoPago: string;
  correoPago: string;
  telefonoPago: string;
  extensionPago: string;
  whatsappPago: string;
  giroNegocio: string;
  nombreGiroNegocio: string;
  redSocial: string;
  nombreRedSocial: string;
  calleEntrega: string;
  numExtEntrega: string;
  numIntEntrega: string;
  coloniaEntrega: string;
  codigoPostalEntrega: string;
  estadoEntrega: string;
  ciudadEntrega: string;
  actaConstitutiva: string | File | null ;
  constanciaFiscal: string | File | null;
  comprobanteDomicilio: string | File | null ;
  edoCuenta: string | File | null ;
  ine: string | File | null ;
  acceptedTerms: boolean;
  acceptedWarranty: boolean;
  acceptedPrivacy: boolean;
}